requires = ["tox>=4"]
env_list = ["3.11", "3.10", "3.9"]

[gh.python]
"3.11" = ["3.11"]
"3.10" = ["3.10"]
"3.9" = ["3.9"]

[env_run_base]
description = "run unit tests"
deps = [
    "pytest>=8"
]
commands = [["pytest", { replace = "posargs", default = ["tests"], extend = true }]]
