- input:
    dataset_type: clinical
    dataset_path: your/data/matrix/path
    output_path: output/matrix/path
    features_cols: true
    en_header: true
    all_numeric: false
    is_raw: true
    steps_to_run:
        - identify_missing_values
        - impute_continuous
        - etc