- input:
    data_matrix: "your/data/matrix/path"
    dataset_type: "clinical/genomics/proteomics/metabolomics"
    current_preprocessing_level: "raw/filtered/normalised/transformed/scaled"
    steps:
        - identify_missing_values
        - impute_continuous
        - ... or simply
        - qc_all
        - etc.
    output_matrix: "output/matrix/path"
    output_report: "output/report/path"
    output_log: "output/log/path"
